name: gg_status_printer
description: Prints progress, success, and error messages with Unicode icons for async operations.
version: 1.1.5
repository: https://github.com/inlavigo/gg_status_printer.git

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_is_github: ^1.0.0
  gg_log: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
